name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install deps
        run: |
          make install || npm ci

      - name: Lint (optional)
        run: |
          if [ -f "eslint.config.js" ] || [ -f ".eslintrc.*" ]; then
            npx eslint . || true
          fi

      - name: Run tests
        run: |
          if make -n test >/dev/null 2>&1; then
            make test
          else
            npm test --ignore-scripts
          fi

      - name: Coverage
        run: |
          if make -n test-coverage >/dev/null 2>&1; then
            make test-coverage
          else
            npm run test:coverage --if-present
          fi

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.node-version }}
          path: |
            coverage
            .coverage
          if-no-files-found: ignore
